---
name: "nightly-main"
on:
    schedule:
        - cron: '42 5 * * *'
    workflow_dispatch:

jobs:
    nightly-main:
        name: "dispatch-nightly-main"
        uses: ./.github/workflows/ci.yml
        with:
            ref: 'main'